-- ==============================================================================
-- SCRIPT 00: ELIMINACIÓN CONTROLADA DE OBJETOS
-- ==============================================================================
-- Propósito : Limpiar todos los objetos antes de reinstalar la solución completa.
-- Ejecutar  : Como SYSTEM en sqlplus antes de correr los scripts 01 al 14.
-- Seguridad : Cada DROP está envuelto en EXCEPTION WHEN OTHERS para ignorar
--             objetos que no existan (idempotente, se puede correr N veces).
-- ==============================================================================

ALTER SESSION SET "_ORACLE_SCRIPT"=true;
SET SERVEROUTPUT ON;

BEGIN DBMS_OUTPUT.PUT_LINE('=== INICIO LIMPIEZA CONTROLADA ==='); END;
/

-- ------------------------------------------------------------------------------
-- 1. JOBS (deben eliminarse primero para no quedar huérfanos)
-- ------------------------------------------------------------------------------
BEGIN DBMS_SCHEDULER.drop_job('APP_CLINICA.JOB_RECORDATORIOS_24H', force => TRUE); EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN DBMS_SCHEDULER.drop_job('SEG_CLINICA.JOB_EXPIRAR_SESIONES',  force => TRUE); EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN DBMS_OUTPUT.PUT_LINE('[1/7] Jobs eliminados.'); END;
/

-- ------------------------------------------------------------------------------
-- 2. TRIGGERS (APP_CLINICA)
-- ------------------------------------------------------------------------------
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER APP_CLINICA.TRG_AUDITORIA_CITAS';     EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER APP_CLINICA.TRG_AUDITORIA_PACIENTES';  EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER APP_CLINICA.TRG_IMPEDIR_EMPATE_CITA'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER APP_CLINICA.TRG_SEQ_CITA_ID';         EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER APP_CLINICA.TRG_FECHA_MODIFICACION';  EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN DBMS_OUTPUT.PUT_LINE('[2/7] Triggers eliminados.'); END;
/

-- ------------------------------------------------------------------------------
-- 3. VISTAS
-- ------------------------------------------------------------------------------
BEGIN EXECUTE IMMEDIATE 'DROP VIEW APP_CLINICA.VW_AGENDA_DIARIA';        EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW APP_CLINICA.VW_DISPONIBILIDAD_MEDICO'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW APP_CLINICA.VW_HISTORIAL_PACIENTE';   EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW APP_CLINICA.VW_RESUMEN_CITAS';        EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW SEG_CLINICA.VW_USUARIOS_ACTIVOS';     EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN DBMS_OUTPUT.PUT_LINE('[3/7] Vistas eliminadas.'); END;
/

-- ------------------------------------------------------------------------------
-- 4. PAQUETES (orden: dependientes primero)
-- ------------------------------------------------------------------------------
BEGIN EXECUTE IMMEDIATE 'DROP PACKAGE APP_CLINICA.PKG_REPORTES';     EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PACKAGE APP_CLINICA.PKG_CONSULTAS';    EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PACKAGE APP_CLINICA.PKG_VALOR';        EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PACKAGE APP_CLINICA.PKG_ADMINISTRACION'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PACKAGE SEG_CLINICA.PKG_SEGURIDAD';    EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN DBMS_OUTPUT.PUT_LINE('[4/7] Paquetes eliminados.'); END;
/

-- ------------------------------------------------------------------------------
-- 5. SINÓNIMOS (APP_CLINICA → SEG_CLINICA)
-- ------------------------------------------------------------------------------
BEGIN EXECUTE IMMEDIATE 'DROP SYNONYM APP_CLINICA.ROLES';       EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SYNONYM APP_CLINICA.USUARIOS';    EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SYNONYM APP_CLINICA.AUDITORIA';   EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SYNONYM APP_CLINICA.SESIONES';    EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SYNONYM APP_CLINICA.PKG_SEGURIDAD'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN DBMS_OUTPUT.PUT_LINE('[5/7] Sinonimos eliminados.'); END;
/

-- ------------------------------------------------------------------------------
-- 6. TABLAS (CASCADE CONSTRAINTS maneja FKs cruzadas automáticamente)
-- Orden inverso de dependencias para claridad, aunque CASCADE lo resuelve.
-- ------------------------------------------------------------------------------
-- APP_CLINICA: hijos primero
BEGIN EXECUTE IMMEDIATE 'DROP TABLE APP_CLINICA.NOTIFICACIONES  CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE APP_CLINICA.CITAS           CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE APP_CLINICA.HORARIOS_MEDICO CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE APP_CLINICA.PACIENTES        CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE APP_CLINICA.ESTADOS_CITA    CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE APP_CLINICA.MEDICOS          CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE APP_CLINICA.ESPECIALIDADES  CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
-- SEG_CLINICA: hijos primero
BEGIN EXECUTE IMMEDIATE 'DROP TABLE SEG_CLINICA.AUDITORIA CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE SEG_CLINICA.SESIONES  CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE SEG_CLINICA.USUARIOS  CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE SEG_CLINICA.ROLES     CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN DBMS_OUTPUT.PUT_LINE('[6/7] Tablas eliminadas.'); END;
/

-- ------------------------------------------------------------------------------
-- 7. SECUENCIAS
-- ------------------------------------------------------------------------------
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE APP_CLINICA.SEQ_ESPECIALIDADES';  EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE APP_CLINICA.SEQ_MEDICOS';         EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE APP_CLINICA.SEQ_PACIENTES';       EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE APP_CLINICA.SEQ_CITAS';           EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE APP_CLINICA.SEQ_NOTIFICACIONES';  EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE APP_CLINICA.SEQ_HORARIOS';        EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEG_CLINICA.SEQ_USUARIOS';        EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEG_CLINICA.SEQ_AUDITORIA';       EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN DBMS_OUTPUT.PUT_LINE('[7/7] Secuencias eliminadas.'); END;
/

BEGIN DBMS_OUTPUT.PUT_LINE('=== LIMPIEZA COMPLETADA — listo para ejecutar 01_esquemas_y_tablas.sql ==='); END;
/
