-- ==============================================================================
-- SCRIPT 01: CREACIÓN DE ESQUEMAS, SECUENCIAS Y TABLAS
-- ==============================================================================
-- Nota: Ejecutar la primera parte conectado como SYSDBA o SYSTEM

-- Habilitar creación de usuarios sin el prefijo C## (Comportamiento Oracle 12c/19c)
ALTER SESSION SET "_ORACLE_SCRIPT"=true;

-- 1. CREACIÓN DE ESQUEMAS (USUARIOS)
BEGIN
   EXECUTE IMMEDIATE 'CREATE USER SEG_CLINICA IDENTIFIED BY "SegClinica2026"';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
GRANT CONNECT, RESOURCE, CREATE VIEW, CREATE JOB TO SEG_CLINICA;
ALTER USER SEG_CLINICA QUOTA UNLIMITED ON USERS;

BEGIN
   EXECUTE IMMEDIATE 'CREATE USER APP_CLINICA IDENTIFIED BY "AppClinica2026"';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
GRANT CONNECT, RESOURCE, CREATE VIEW, CREATE JOB, CREATE SYNONYM TO APP_CLINICA;
ALTER USER APP_CLINICA QUOTA UNLIMITED ON USERS;

-- ==============================================================================
-- TABLAS Y SECUENCIAS: SEG_CLINICA
-- ==============================================================================
CREATE SEQUENCE SEG_CLINICA.SEQ_USUARIOS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEG_CLINICA.SEQ_AUDITORIA START WITH 1 INCREMENT BY 1;

CREATE TABLE SEG_CLINICA.ROLES (
    ROL_ID NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(50) NOT NULL UNIQUE,
    DESCRIPCION VARCHAR2(200),
    ESTADO CHAR(1) DEFAULT 'A' CHECK (ESTADO IN ('A', 'I'))
);

CREATE TABLE SEG_CLINICA.USUARIOS (
    USUARIO_ID NUMBER PRIMARY KEY,
    USERNAME VARCHAR2(50) NOT NULL UNIQUE,
    PASSWORD_HASH RAW(64) NOT NULL,
    NOMBRE_COMPLETO VARCHAR2(150) NOT NULL,
    EMAIL VARCHAR2(100),
    ROL_ID NUMBER NOT NULL,
    MEDICO_ID NUMBER NULL,
    ESTADO CHAR(1) DEFAULT 'A' CHECK (ESTADO IN ('A', 'I')),
    FECHA_CREACION TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    ULTIMO_ACCESO TIMESTAMP,
    CONSTRAINT FK_USUARIO_ROL FOREIGN KEY (ROL_ID) REFERENCES SEG_CLINICA.ROLES(ROL_ID)
    -- FK_USUARIO_MEDICO se añade en el script de Grants porque la tabla MEDICOS aún no existe
);

CREATE TABLE SEG_CLINICA.SESIONES (
    SESION_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USUARIO_ID NUMBER NOT NULL,
    TOKEN VARCHAR2(128) NOT NULL UNIQUE,
    FECHA_INICIO TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    FECHA_EXPIRACION TIMESTAMP NOT NULL,
    IP_CLIENTE VARCHAR2(45),
    ESTADO CHAR(1) DEFAULT 'A' CHECK (ESTADO IN ('A', 'E', 'C')),
    CONSTRAINT FK_SESION_USUARIO FOREIGN KEY (USUARIO_ID) REFERENCES SEG_CLINICA.USUARIOS(USUARIO_ID)
);

CREATE TABLE SEG_CLINICA.AUDITORIA (
    AUDITORIA_ID NUMBER PRIMARY KEY,
    USUARIO_ID NUMBER NOT NULL,
    TABLA_AFECTADA VARCHAR2(50) NOT NULL,
    OPERACION VARCHAR2(10) NOT NULL CHECK (OPERACION IN ('INSERT', 'UPDATE', 'DELETE')),
    REGISTRO_ID NUMBER,
    DATOS_ANTES CLOB,
    DATOS_DESPUES CLOB,
    FECHA_HORA TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    IP_CLIENTE VARCHAR2(45)
);

-- ==============================================================================
-- TABLAS Y SECUENCIAS: APP_CLINICA
-- ==============================================================================
CREATE SEQUENCE APP_CLINICA.SEQ_ESPECIALIDADES START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE APP_CLINICA.SEQ_MEDICOS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE APP_CLINICA.SEQ_PACIENTES START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE APP_CLINICA.SEQ_CITAS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE APP_CLINICA.SEQ_NOTIFICACIONES START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE APP_CLINICA.SEQ_HORARIOS START WITH 1 INCREMENT BY 1;

CREATE TABLE APP_CLINICA.ESPECIALIDADES (
    ESPECIALIDAD_ID NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL UNIQUE,
    DESCRIPCION VARCHAR2(300),
    ESTADO CHAR(1) DEFAULT 'A' CHECK (ESTADO IN ('A', 'I'))
);

CREATE TABLE APP_CLINICA.MEDICOS (
    MEDICO_ID NUMBER PRIMARY KEY,
    NOMBRES VARCHAR2(100) NOT NULL,
    APELLIDOS VARCHAR2(100) NOT NULL,
    NRO_COLEGIATURA VARCHAR2(20) NOT NULL UNIQUE,
    ESPECIALIDAD_ID NUMBER NOT NULL,
    TELEFONO VARCHAR2(15),
    EMAIL VARCHAR2(100),
    ESTADO CHAR(1) DEFAULT 'A' CHECK (ESTADO IN ('A', 'I')),
    CONSTRAINT FK_MEDICO_ESPEC FOREIGN KEY (ESPECIALIDAD_ID) REFERENCES APP_CLINICA.ESPECIALIDADES(ESPECIALIDAD_ID)
);

CREATE TABLE APP_CLINICA.HORARIOS_MEDICO (
    HORARIO_ID NUMBER PRIMARY KEY,
    MEDICO_ID NUMBER NOT NULL,
    DIA_SEMANA NUMBER(1) NOT NULL CHECK (DIA_SEMANA BETWEEN 1 AND 7),
    HORA_INICIO VARCHAR2(5) NOT NULL,
    HORA_FIN VARCHAR2(5) NOT NULL,
    DURACION_CITA_MIN NUMBER NOT NULL,
    ESTADO CHAR(1) DEFAULT 'A' CHECK (ESTADO IN ('A', 'I')),
    CONSTRAINT FK_HORARIO_MEDICO FOREIGN KEY (MEDICO_ID) REFERENCES APP_CLINICA.MEDICOS(MEDICO_ID)
);

CREATE TABLE APP_CLINICA.PACIENTES (
    PACIENTE_ID NUMBER PRIMARY KEY,
    NOMBRES VARCHAR2(100) NOT NULL,
    APELLIDOS VARCHAR2(100) NOT NULL,
    DNI VARCHAR2(15) NOT NULL UNIQUE,
    FECHA_NACIMIENTO DATE,
    TELEFONO VARCHAR2(15) NOT NULL,
    EMAIL VARCHAR2(100),
    DIRECCION VARCHAR2(200),
    ESTADO CHAR(1) DEFAULT 'A' CHECK (ESTADO IN ('A', 'I')),
    FECHA_REGISTRO TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE APP_CLINICA.ESTADOS_CITA (
    ESTADO_CITA_ID NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(30) NOT NULL UNIQUE,
    DESCRIPCION VARCHAR2(200)
);

CREATE TABLE APP_CLINICA.CITAS (
    CITA_ID NUMBER PRIMARY KEY,
    PACIENTE_ID NUMBER NOT NULL,
    MEDICO_ID NUMBER NOT NULL,
    ESPECIALIDAD_ID NUMBER NOT NULL,
    FECHA_CITA DATE NOT NULL,
    HORA_INICIO VARCHAR2(5) NOT NULL,
    HORA_FIN VARCHAR2(5) NOT NULL,
    ESTADO_CITA_ID NUMBER NOT NULL,
    MOTIVO_CONSULTA VARCHAR2(500),
    MOTIVO_CANCELACION VARCHAR2(500),
    OBSERVACIONES VARCHAR2(500),
    USUARIO_CREACION NUMBER NOT NULL, 
    FECHA_CREACION TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    FECHA_MODIFICACION TIMESTAMP,
    CONSTRAINT FK_CITA_PACIENTE FOREIGN KEY (PACIENTE_ID) REFERENCES APP_CLINICA.PACIENTES(PACIENTE_ID),
    CONSTRAINT FK_CITA_MEDICO FOREIGN KEY (MEDICO_ID) REFERENCES APP_CLINICA.MEDICOS(MEDICO_ID),
    CONSTRAINT FK_CITA_ESPEC FOREIGN KEY (ESPECIALIDAD_ID) REFERENCES APP_CLINICA.ESPECIALIDADES(ESPECIALIDAD_ID),
    CONSTRAINT FK_CITA_ESTADO FOREIGN KEY (ESTADO_CITA_ID) REFERENCES APP_CLINICA.ESTADOS_CITA(ESTADO_CITA_ID)
);

CREATE TABLE APP_CLINICA.NOTIFICACIONES (
    NOTIFICACION_ID NUMBER PRIMARY KEY,
    CITA_ID NUMBER NOT NULL,
    PACIENTE_ID NUMBER NOT NULL,
    TIPO VARCHAR2(30) NOT NULL,
    MENSAJE VARCHAR2(500) NOT NULL,
    FECHA_GENERACION TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    LEIDA CHAR(1) DEFAULT 'N' CHECK (LEIDA IN ('S', 'N')),
    CONSTRAINT FK_NOTIF_CITA FOREIGN KEY (CITA_ID) REFERENCES APP_CLINICA.CITAS(CITA_ID),
    CONSTRAINT FK_NOTIF_PACIENTE FOREIGN KEY (PACIENTE_ID) REFERENCES APP_CLINICA.PACIENTES(PACIENTE_ID)
);

-- ==============================================================================
-- 5. ÍNDICES (JUSTIFICADOS PARA CONSULTAS RELEVANTES)
-- ==============================================================================

-- Índice en PACIENTE_ID (CITAS): Mejora búsquedas del historial clínico (Requerimiento CON02)
CREATE INDEX APP_CLINICA.IDX_CITAS_PACIENTE ON APP_CLINICA.CITAS(PACIENTE_ID);

-- Índice en MEDICO_ID y FECHA_CITA (CITAS): Vital para verificar disponibilidad y la agenda diaria (Requerimientos VAL04, CON01)
CREATE INDEX APP_CLINICA.IDX_CITAS_MEDICO_FECHA ON APP_CLINICA.CITAS(MEDICO_ID, FECHA_CITA);

-- Índice en ESTADO_CITA_ID (CITAS): Optimiza reportes estadísticos por estado y cancelaciones (Requerimientos CON04, REP03)
CREATE INDEX APP_CLINICA.IDX_CITAS_ESTADO ON APP_CLINICA.CITAS(ESTADO_CITA_ID);

-- Índice en DNI (PACIENTES): Para agilizar las búsquedas de pacientes en recepción (Requerimiento CON05)
CREATE INDEX APP_CLINICA.IDX_PACIENTES_DNI ON APP_CLINICA.PACIENTES(DNI);

-- Índice en DIA_SEMANA (HORARIOS_MEDICO): Acelera la búsqueda de franjas libres (Requerimiento VAL05)
CREATE INDEX APP_CLINICA.IDX_HORARIOS_DIA ON APP_CLINICA.HORARIOS_MEDICO(DIA_SEMANA);

-- Índice en USUARIO_ID (AUDITORIA): Mejora filtrado de auditoría por usuario (Requerimiento SEG05)
CREATE INDEX SEG_CLINICA.IDX_AUDITORIA_USUARIO ON SEG_CLINICA.AUDITORIA(USUARIO_ID);
