-- ==============================================================================
-- SCRIPT 02: GRANTS, SINÓNIMOS Y LLAVES FORÁNEAS CRUZADAS
-- ==============================================================================
-- Nota: Ejecutar conectado como SYSDBA o desde APP_CLINICA / SEG_CLINICA según corresponda.

-- 1. PERMISOS DE SEG_CLINICA HACIA APP_CLINICA
GRANT SELECT ON SEG_CLINICA.ROLES TO APP_CLINICA;
GRANT SELECT ON SEG_CLINICA.USUARIOS TO APP_CLINICA;
GRANT INSERT ON SEG_CLINICA.AUDITORIA TO APP_CLINICA;
GRANT SELECT, UPDATE ON SEG_CLINICA.SESIONES TO APP_CLINICA;

-- Permisos de ejecución de paquetes y objetos de seguridad
GRANT EXECUTE ON SEG_CLINICA.PKG_SEGURIDAD TO APP_CLINICA;
GRANT INSERT, UPDATE ON SEG_CLINICA.USUARIOS TO APP_CLINICA;
GRANT SELECT ON SEG_CLINICA.SEQ_USUARIOS TO APP_CLINICA;

-- 2. PERMISOS DE APP_CLINICA HACIA SEG_CLINICA
GRANT REFERENCES ON APP_CLINICA.MEDICOS TO SEG_CLINICA;

-- 3. CREAR LA FK CRUZADA (El usuario de SEG_CLINICA hace referencia al médico)
ALTER TABLE SEG_CLINICA.USUARIOS ADD CONSTRAINT FK_USUARIO_MEDICO 
FOREIGN KEY (MEDICO_ID) REFERENCES APP_CLINICA.MEDICOS(MEDICO_ID);

-- 4. SINÓNIMOS PRIVADOS EN APP_CLINICA
-- Para no tener que escribir SEG_CLINICA.TABLA cada vez
CREATE OR REPLACE SYNONYM APP_CLINICA.ROLES FOR SEG_CLINICA.ROLES;
CREATE OR REPLACE SYNONYM APP_CLINICA.USUARIOS FOR SEG_CLINICA.USUARIOS;
CREATE OR REPLACE SYNONYM APP_CLINICA.AUDITORIA FOR SEG_CLINICA.AUDITORIA;
CREATE OR REPLACE SYNONYM APP_CLINICA.SESIONES FOR SEG_CLINICA.SESIONES;

-- Para DBMS_CRYPTO (requiere grant execute por SYSDBA/SYSTEM)
GRANT EXECUTE ON SYS.DBMS_CRYPTO TO SEG_CLINICA;
GRANT EXECUTE ON SYS.DBMS_CRYPTO TO APP_CLINICA;

-- 5. LLAVES FORÁNEAS ADICIONALES PARA CUMPLIMIENTO DEL SPEC
GRANT REFERENCES ON SEG_CLINICA.USUARIOS TO APP_CLINICA;

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE APP_CLINICA.CITAS ADD CONSTRAINT FK_CITA_USUARIO FOREIGN KEY (USUARIO_CREACION) REFERENCES SEG_CLINICA.USUARIOS(USUARIO_ID)';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE SEG_CLINICA.AUDITORIA ADD CONSTRAINT FK_AUDITORIA_USUARIO FOREIGN KEY (USUARIO_ID) REFERENCES SEG_CLINICA.USUARIOS(USUARIO_ID)';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
